name: Android build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - name: "ARM32"
            arch: "armeabi-v7a"

          - name: "ARM64"
            arch: "arm64-v8a"

    name: Linux -> Android-${{ matrix.name }}

    steps:
    - name: Clean Disk
      uses: DiligentGraphics/github-action/clean-disk-ubuntu@v4

    - name: Checkout
      uses: DiligentGraphics/github-action/checkout@v4

    - name: Create CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/BuildTools/Scripts/github_actions
        chmod +x create_cmake.sh
        ./create_cmake.sh "$GITHUB_WORKSPACE"

    - name: Set up build environment
      if: success()
      uses: DiligentGraphics/github-action/setup-build-env@v4
      with:
        platform: Android

    - name: Build with Gradle
      if: success()
      env:
        ANDROID_ARCH: ${{ matrix.arch }}
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/Android
        chmod +x gradlew
        ./gradlew buildRelease
        echo -e "\nRemaining disk space: $(df -BG / | awk 'NR==2 {print $4}' | sed 's/G//') GB"
