name: Linux

on: [push, pull_request]

jobs:
  build-gcc-9:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: ubuntu-latest
    name: Linux x64, GCC 9, ${{ matrix.config }}

    steps:
    - name: Clone DiligentSamples
      uses: actions/checkout@v2
      with:
        path:       DiligentSamples
        submodules: recursive

    - name: Clone DiligentFX
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentFX'
        path:       DiligentFX
        submodules: recursive

    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentTools'
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Format validation
      working-directory: DiligentSamples
      shell: bash
      run: |
        cd ./BuildTools/FormatValidation
        ./validate_format_linux.sh

    - name: Configure dependencies
      if: success()
      run: |
        sudo apt-get install build-essential libx11-dev libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Configure CMake
      if: success()
      env:
        CC: gcc-9
        CXX: g++-9
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/BuildTools/Scripts/github_actions
        chmod +x create_cmake.sh
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        chmod +x configure_cmake.sh
        ./configure_cmake.sh "linux" "${{runner.workspace}}" ${{ matrix.config }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2


  build-clang-10:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: ubuntu-latest
    name: Linux x64, Clang 10, ${{ matrix.config }}

    steps:
    - name: Clone DiligentSamples
      uses: actions/checkout@v2
      with:
        path:       DiligentSamples
        submodules: recursive

    - name: Clone DiligentFX
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentFX'
        path:       DiligentFX
        submodules: recursive

    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentTools'
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Format validation
      working-directory: DiligentSamples
      shell: bash
      run: |
        cd ./BuildTools/FormatValidation
        ./validate_format_linux.sh

    - name: Configure dependencies
      if: success()
      run: |
        sudo apt-get install build-essential libx11-dev libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Configure CMake
      if: success()
      env:
        CC: clang-10
        CXX: clang++-10
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/BuildTools/Scripts/github_actions
        chmod +x create_cmake.sh
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        chmod +x configure_cmake.sh
        ./configure_cmake.sh "linux" "${{runner.workspace}}" ${{ matrix.config }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2
