name: UWP

on: [push, pull_request]

jobs:
  build-uwp:
    strategy:
      matrix:
        toolset: [x64]
        config: [Debug, Release]

    runs-on: windows-latest
    name: UWP, ${{ matrix.config }} ${{ matrix.toolset }}

    steps:
    - name: Clone DiligentSamples
      uses: actions/checkout@v2
      with:
        path:       DiligentSamples
        submodules: recursive

    - name: Clone DiligentFX
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentFX'
        path:       DiligentFX
        submodules: recursive
        
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentTools'
        path:       DiligentTools
        submodules: recursive
        
    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Format validation
      working-directory: DiligentSamples
      shell: cmd
      run: |
        cd BuildTools\FormatValidation
        validate_format_win.bat

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "uwp" "${{runner.workspace}}" ${{ matrix.config }} ${{ matrix.toolset }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2
