name: Windows

on: [push, pull_request]

jobs:
  build-win10:
    strategy:
      matrix:
        toolset: [Win32, x64]
        config: [Debug, Release]

    runs-on: windows-latest
    name: Win10 -> ${{ matrix.toolset }}, ${{ matrix.config }}

    steps:
    - name: Clone DiligentSamples
      uses: actions/checkout@v2
      with:
        path:       DiligentSamples
        submodules: recursive

    - name: Clone DiligentFX
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentFX'
        path:       DiligentFX
        submodules: recursive

    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentTools'
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "win" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2


  build-win10-dev:
    strategy:
      matrix:
        toolset: [x64]
        config: [RelWithDebInfo]

    runs-on: windows-latest
    name: Win10 -> ${{ matrix.toolset }}, ${{ matrix.config }}, DEVELOPMENT

    steps:
    - name: Clone DiligentSamples
      uses: actions/checkout@v2
      with:
        path:       DiligentSamples
        submodules: recursive

    - name: Clone DiligentFX
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentFX'
        path:       DiligentFX
        submodules: recursive

    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentTools'
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "win" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }} "-DDILIGENT_DEVELOPMENT=ON"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2


  build-win8:
    strategy:
      matrix:
        toolset: [Win32, x64]
        config: [Debug, Release]

    runs-on: windows-latest
    name: Win10 -> Win8.1-${{ matrix.toolset }}, ${{ matrix.config }}

    steps:
    - name: Clone DiligentSamples
      uses: actions/checkout@v2
      with:
        path:       DiligentSamples
        submodules: recursive

    - name: Clone DiligentFX
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentFX'
        path:       DiligentFX
        submodules: recursive

    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentTools'
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "win" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }} "-DCMAKE_SYSTEM_VERSION=8.1"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2
